//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLKK.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CLKKEntities : DbContext
    {
        public CLKKEntities()
            : base("name=CLKKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CMS_Album> CMS_Album { get; set; }
        public virtual DbSet<CMS_Comments> CMS_Comments { get; set; }
        public virtual DbSet<CMS_Config> CMS_Config { get; set; }
        public virtual DbSet<CMS_ContactUs> CMS_ContactUs { get; set; }
        public virtual DbSet<CMS_DocType> CMS_DocType { get; set; }
        public virtual DbSet<CMS_Document> CMS_Document { get; set; }
        public virtual DbSet<CMS_Domain> CMS_Domain { get; set; }
        public virtual DbSet<CMS_Email> CMS_Email { get; set; }
        public virtual DbSet<CMS_Gallery> CMS_Gallery { get; set; }
        public virtual DbSet<CMS_Map> CMS_Map { get; set; }
        public virtual DbSet<CMS_Media> CMS_Media { get; set; }
        public virtual DbSet<CMS_MediaGroup> CMS_MediaGroup { get; set; }
        public virtual DbSet<CMS_News> CMS_News { get; set; }
        public virtual DbSet<CMS_Notice> CMS_Notice { get; set; }
        public virtual DbSet<CMS_Question> CMS_Question { get; set; }
        public virtual DbSet<CMS_SlideShow> CMS_SlideShow { get; set; }
        public virtual DbSet<CMS_Social> CMS_Social { get; set; }
        public virtual DbSet<CMS_Topic> CMS_Topic { get; set; }
        public virtual DbSet<CMS_TopicFlag> CMS_TopicFlag { get; set; }
        public virtual DbSet<CMS_TopicLink> CMS_TopicLink { get; set; }
        public virtual DbSet<CMS_UserConfig> CMS_UserConfig { get; set; }
        public virtual DbSet<CMS_UserCounter> CMS_UserCounter { get; set; }
        public virtual DbSet<CMS_UserGroup> CMS_UserGroup { get; set; }
        public virtual DbSet<CMS_Users> CMS_Users { get; set; }
        public virtual DbSet<Setting> Setting { get; set; }
        public virtual DbSet<TD_CoquanQuanly> TD_CoquanQuanly { get; set; }
        public virtual DbSet<TD_Diadanh> TD_Diadanh { get; set; }
        public virtual DbSet<TD_Loaiquantrac> TD_Loaiquantrac { get; set; }
        public virtual DbSet<TD_PPLaymau> TD_PPLaymau { get; set; }
        public virtual DbSet<TD_QCVN> TD_QCVN { get; set; }
        public virtual DbSet<TD_Tramquantrac> TD_Tramquantrac { get; set; }
        public virtual DbSet<TD_ThongsoKetqua> TD_ThongsoKetqua { get; set; }
        public virtual DbSet<TD_Laymau> TD_Laymau { get; set; }
        public virtual DbSet<TD_Thongso> TD_Thongso { get; set; }
        public virtual DbSet<TD_Thongsomau> TD_Thongsomau { get; set; }
        public virtual DbSet<TD_Kiemduyet> TD_Kiemduyet { get; set; }
    }
}
