//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLKK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_Users
    {
        public string Users_ID { get; set; }
        public string Users_Name { get; set; }
        public string Password { get; set; }
        public string UserGroup_ID { get; set; }
    
        public virtual CMS_UserGroup CMS_UserGroup { get; set; }
    }
}
