//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLKK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_UserCounter
    {
        public int ID { get; set; }
        public Nullable<int> day { get; set; }
        public Nullable<int> onlineDay { get; set; }
        public Nullable<int> week { get; set; }
        public Nullable<int> onlineWeek { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> onlineMonth { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> onlineYear { get; set; }
        public Nullable<int> sum { get; set; }
    }
}
