//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLKK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_Email
    {
        public int Email_ID { get; set; }
        public string Email { get; set; }
        public System.DateTime CreatedBy { get; set; }
        public bool IsActive { get; set; }
    }
}
