//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLKK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_Document
    {
        public int Document_ID { get; set; }
        public string Topic_ID { get; set; }
        public string Document_Name { get; set; }
        public Nullable<int> DocType_ID { get; set; }
        public Nullable<int> Provider_ID { get; set; }
        public Nullable<int> Filed_ID { get; set; }
        public string Contents { get; set; }
        public string NoCode { get; set; }
        public string SignerName { get; set; }
        public Nullable<System.DateTime> PromDate { get; set; }
        public Nullable<System.DateTime> EffectDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string FileSource { get; set; }
        public string FileGenKey { get; set; }
        public string IsURL { get; set; }
        public Nullable<int> IsDownload { get; set; }
        public Nullable<int> IsLang { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> IsOrder { get; set; }
        public System.DateTime CreatedBy { get; set; }
        public string UserName { get; set; }
    
        public virtual CMS_DocType CMS_DocType { get; set; }
        public virtual CMS_Topic CMS_Topic { get; set; }
    }
}
