//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLKK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_Comments
    {
        public int Comments_ID { get; set; }
        public string News_ID { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Contents { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsActive { get; set; }
        public string Avartar { get; set; }
    
        public virtual CMS_News CMS_News { get; set; }
    }
}
