//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLKK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_MediaGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMS_MediaGroup()
        {
            this.CMS_Media = new HashSet<CMS_Media>();
        }
    
        public int SlideGroup_ID { get; set; }
        public string SlideGroup_Name { get; set; }
        public string Topic_ID { get; set; }
        public bool IsHot { get; set; }
        public Nullable<int> IsPosition { get; set; }
        public string Des { get; set; }
        public Nullable<int> IsPlay { get; set; }
        public Nullable<int> IsLang { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> IsOrder { get; set; }
        public System.DateTime CreatedBy { get; set; }
        public string UserName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMS_Media> CMS_Media { get; set; }
        public virtual CMS_Topic CMS_Topic { get; set; }
    }
}
