//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLKK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_TopicLink
    {
        public int TopicLink_ID { get; set; }
        public string TopicLink_Name { get; set; }
        public string IsUrl { get; set; }
        public Nullable<int> IsOrder { get; set; }
    }
}
