//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLKK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_Config
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMS_Config()
        {
            this.CMS_UserConfig = new HashSet<CMS_UserConfig>();
        }
    
        public string Module_ID { get; set; }
        public string Module_Name { get; set; }
        public string Module_Icon { get; set; }
        public bool IsMain { get; set; }
        public bool Status { get; set; }
        public Nullable<int> IsOrder { get; set; }
        public Nullable<int> IsFlag { get; set; }
        public Nullable<int> IsType { get; set; }
        public string Parent_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMS_UserConfig> CMS_UserConfig { get; set; }
    }
}
