//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLKK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_Media
    {
        public int SlideShow_ID { get; set; }
        public string SlideShow_Name { get; set; }
        public Nullable<int> SlideGroup_ID { get; set; }
        public Nullable<int> IsType { get; set; }
        public string FlvImage { get; set; }
        public string Contents { get; set; }
        public string Images { get; set; }
        public string IsUrl { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> IsLang { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> IsOrder { get; set; }
        public System.DateTime CreatedBy { get; set; }
        public string UserName { get; set; }
        public Nullable<int> IsView { get; set; }
        public Nullable<int> IsLike { get; set; }
        public Nullable<int> Dislike { get; set; }
    
        public virtual CMS_MediaGroup CMS_MediaGroup { get; set; }
    }
}
