//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLKK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_Domain
    {
        public int Domain_ID { get; set; }
        public string Domain_Name { get; set; }
        public string Domain_Address { get; set; }
        public Nullable<System.DateTime> InOfDate { get; set; }
        public Nullable<System.DateTime> OutOfDate { get; set; }
        public Nullable<int> IsOrder { get; set; }
        public bool IsActive { get; set; }
    }
}
