//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLKK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_News
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMS_News()
        {
            this.CMS_Comments = new HashSet<CMS_Comments>();
        }
    
        public string News_ID { get; set; }
        public string Topic_ID { get; set; }
        public string News_Name { get; set; }
        public bool IsHot { get; set; }
        public string Images { get; set; }
        public Nullable<int> NewType { get; set; }
        public string Contents { get; set; }
        public string Details { get; set; }
        public string Keywords { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> IsVisitor { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> IsOrder { get; set; }
        public System.DateTime CreatedBy { get; set; }
        public string Users_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMS_Comments> CMS_Comments { get; set; }
        public virtual CMS_Topic CMS_Topic { get; set; }
    }
}
