//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLKK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public string ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> IsOrder { get; set; }
        public string VN { get; set; }
        public string EN { get; set; }
    }
}
