//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLKK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_Kiemduyet
    {
        public string Kiemduyet_ID { get; set; }
        public string Tramquantrac_ID { get; set; }
        public bool Giatriam { get; set; }
        public bool Ngoaikhoang { get; set; }
        public string Loaiquantrac_ID { get; set; }
        public System.DateTime Ngaytao { get; set; }
        public string Nguoitao { get; set; }
        public string Thongsomau_Ten { get; set; }
        public bool Khongcogiatri { get; set; }
    
        public virtual TD_Tramquantrac TD_Tramquantrac { get; set; }
    }
}
