//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLKK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_ThongsoKetqua
    {
        public string ThongsoKetqua_ID { get; set; }
        public string Tenthongso { get; set; }
        public string Donvi { get; set; }
        public Nullable<double> Giatrithongso { get; set; }
        public string Ghichu { get; set; }
        public string Thongso_ID { get; set; }
    
        public virtual TD_Thongso TD_Thongso { get; set; }
    }
}
