//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLKK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_Tramquantrac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TD_Tramquantrac()
        {
            this.TD_Laymau = new HashSet<TD_Laymau>();
            this.TD_Thongso = new HashSet<TD_Thongso>();
            this.TD_Kiemduyet = new HashSet<TD_Kiemduyet>();
        }
    
        public string Tramquantrac_ID { get; set; }
        public string Tramquantrac_Ten { get; set; }
        public Nullable<int> STT { get; set; }
        public bool Trangthai { get; set; }
        public string Loaiquantrac_ID { get; set; }
        public string MaTram { get; set; }
        public Nullable<double> Kinhdo { get; set; }
        public Nullable<double> Vido { get; set; }
        public string Diadanh_ID { get; set; }
        public Nullable<int> Loai { get; set; }
        public string CoquanQuanly_ID { get; set; }
        public Nullable<int> TansuatNhanDL { get; set; }
        public string Diachi { get; set; }
        public string Mota { get; set; }
        public string QCVN_ID { get; set; }
        public Nullable<int> LoaiQCVN { get; set; }
        public Nullable<double> QCVN_Heso1 { get; set; }
        public Nullable<double> QCVN_Heso2 { get; set; }
        public System.DateTime Ngaytao { get; set; }
        public string Nguoitao { get; set; }
    
        public virtual TD_CoquanQuanly TD_CoquanQuanly { get; set; }
        public virtual TD_Diadanh TD_Diadanh { get; set; }
        public virtual TD_Loaiquantrac TD_Loaiquantrac { get; set; }
        public virtual TD_QCVN TD_QCVN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TD_Laymau> TD_Laymau { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TD_Thongso> TD_Thongso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TD_Kiemduyet> TD_Kiemduyet { get; set; }
    }
}
