//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLKK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_Thongsomau
    {
        public string Thongsomau_ID { get; set; }
        public string Thongsomau_Ten { get; set; }
        public string Loaiquantrac_ID { get; set; }
        public string Donvi { get; set; }
        public int STT { get; set; }
        public bool Trangthai { get; set; }
        public string PPLaymau_ID { get; set; }
        public System.DateTime Ngaytao { get; set; }
        public string Nguoitao { get; set; }
        public Nullable<double> Max { get; set; }
        public Nullable<double> Min { get; set; }
        public Nullable<double> Delta { get; set; }
    
        public virtual TD_Loaiquantrac TD_Loaiquantrac { get; set; }
        public virtual TD_PPLaymau TD_PPLaymau { get; set; }
    }
}
